version: '3.2'

services:
  app:
    image: kevin/todos-api
    ports:
      - 3000:3000
    environment:
      - PG_USERNAME=postgres
      - PG_PASSWORD=secret
      - PG_HOST=pg
      - PG_PORT=5432

  pg:
    image: postgres:10-alpine
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      - PG_USERNAME=postgres
      - PG_PASSWORD=secret

